### ISSUE TITLE
Group spent times by users

### ISSUE THREAD

**Issue by saitho** [lucasaba/GitlabTimeTrack#24]
I think it would be nice if you could see how long each participant spent on a task or on the whole project.
GitLab API does not provide that information with their time tracking functionality - but time operations leave a note (Note API) in the task, which can be processed to find out how much time a user has spent.

I already did something there - but it's rather "hacky" than good style ^^

**Comment by lucasaba** [comment]
You mean using this: /projects/:id/issues/:issue_iid/notes

I get this answer:
```
{
        "id": 2238,
        "body": "added 15m of time spent at 2017-12-15",
        "attachment": null,
        "author": {
            "id": 2,
            "name": "Luca Saba",
            "username": "luca",
            "state": "active",
            "avatar_url": "https://secure.gravatar.com/avatar/938e6d7a5a30b60c501738038779369a?s=80&d=identicon",
            "web_url": "https://gitlab.mmxforge.net/luca"
        },
        "created_at": "2017-12-15T14:29:50.340Z",
        "updated_at": "2017-12-15T14:29:50.340Z",
        "system": true,
        "noteable_id": 599,
        "noteable_type": "Issue",
        "noteable_iid": 339
    }
```
Sounds good! Do you know if there's any documentation on that ? Just to have an exhaustive list of possible time tracking messages.

**Comment by lucasaba** [comment]
I've found these messages:

- added 1w 4d 5h of time spent
- subtracted 1w 4d 5h of time spent
- removed time spent

on spec/services/system_note_service_spec.rb

**Comment by nkprince007** [comment]
Any progress on this issue? @lucasaba

**Comment by lucasaba** [comment]
Not yet.

**Comment by lucasaba** [comment]
@saitho @nkprince007 anyone knows of an open source project on which I could test the user's time spent ? I mean, I'm writing the code but I'd like to test if it works on a real team project....

**Comment by nkprince007** [comment]
We do that but our projects aren't open source.
