### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by nkprince007** [lucasaba/GitlabTimeTrack#26]
Please use docker so that I don't have to install all dependencies. For non PHP developers, it will be a great boon.

**Comment by lucasaba** [comment]
I'm not very...confident with docker. Could you give me some hint ?

**Comment by nkprince007** [comment]
Sure. For starters, you can checkout https://docs.docker.com/samples/library/php/#with-command-line. If you need any more specific information, drop a comment below.

**Comment by nkprince007** [comment]
The point of having Docker is to decouple the stack into individual services. If you're having hard time understanding the concepts of docker and compose, just leave it for now. I'll try to make a pull request during the weekend. Thanks for looking into the issue though. Appreciate your concern.

However, I would really appreciate your concern, if you could provide me with the necessary configuration files for apache, your recommended `php.ini` configuration and the list of any additional PHP extensions used.

Also, do mention if it requires any additional package installations via `apt-get`.
