### ISSUE TITLE
GitLab 404 Not Found

### ISSUE THREAD

**Issue by AdrienPoupa** [lucasaba/GitlabTimeTrack#30]
Hi,

Thanks for the project!

Out of the box, I faced this issue:

```
request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ClientException: "Client error: `GET https://gitlab/api/projects?page=1&per_page=100` resulted in a `404 Not Found` response" 
```

The URL is missing the /. Adding a trailing slash at the end of it in the docker compose fixed it:

```
GITLAB_SERVER_URL: https://gitlab.com/api/v4
```

modified to

```
GITLAB_SERVER_URL: https://gitlab.com/api/v4/
```

Maybe Guzzle changed and caused this

**Comment by lucasaba** [comment]
Thanks Adrien!
I'll give it a look. It's....quite some time I'm not watching this project :-P

**Comment by lucasaba** [comment]
Yep! You were right. There's something which confuses me regarding EightPoints GuzzleBundle.

Anyway, I've made a big upgrade to the project. Now, with version2, it is completely a symfony 5 project completely dockerized.

You can configure it to use your existing DB. Only the code is not BC.

**Comment by AdrienPoupa** [comment]
Wow! This is awesome, thanks for the amazing update!
