### ISSUE TITLE
Twig_Error_Runtime when updating project that has no estimates

### ISSUE THREAD

**Issue by saitho** [lucasaba/GitlabTimeTrack#5]
I've imported a GitLab project and clicked the "update" button to update the times.
I haven't set an estimate for each task, which probably is why I get the exception:

> `An exception has been thrown during the rendering of a template ("Warning: Division by zero").`

>in app\Resources\views\default\view_project_issues.html.twig (line 22)
>{% set completition_percentage = (issue.totalTimeSpent/issue.timeEstimate)*100 %}

**Comment by lucasaba** [comment]
You're absolutely right!

I have to find a way to visualize this concept of time spent against no estimate in a progress bar. Thank you for pointing that out!
